---
title: "Projection"
author: "Courtney Giebink"
date: "1/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Models

```{r echo=FALSE}
library(lme4)
library(lmerTest)
library(tidyverse)
library(r2glmm)
library(stringr)
```


### Tree ring only

```{r}
load(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/varmt_df_z.Rdata")
load(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/varmt_pp_z.Rdata")
load(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/varmt_es_z.Rdata")
varmt_df_an <- varmt_df_z %>%
  dplyr::select(PLT_CN,TRE_CN,Year,dds,z.DIA_C,z.CR_fvs,
                z.BAL,z.SDI,z.SICOND,z.SLOPE,z.solrad_MayAug,)
an_df <- lmer(log(dds)~
                  #tree variables
                 z.DIA_C+ I(z.DIA_C^2)+#remove log due to standardization
                 z.CR_fvs+
                 #competition/density
                 z.SDI+#remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #z.solrad_MayAug+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_df_an)
varmt_pp_an <- varmt_pp_z %>%
  dplyr::select(PLT_CN,TRE_CN,Year,dds,z.DIA_C,
                z.BAL,z.SDI,z.SICOND)
an_pp <- lmer(log(dds)~
                     #tree variables
                     z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                     #competition/density
                     z.BAL+ #remove /100 due to standardization
                     #site variables
                     z.SICOND+
                     #random effects
                     (1+z.DIA_C|TRE_CN)+(1|Year),
                   control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
                   data = varmt_pp_an)
varmt_es_an <- varmt_es_z %>%
  dplyr::select(PLT_CN,TRE_CN,Year,dds,z.DIA_C,z.CR,
                z.BAL,z.SDI,z.SICOND,z.SLOPE,z.solrad_MayAug)
an_es <- lmer(log(dds)~
                 #tree variables
                 z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                 z.CR+
                 #competition/density
                 z.BAL+#z.PCCF+z.CCF+ #remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_es_an)
```

```{r}
#plot r2
r2_df <- as.data.frame(r2beta(an_df))
r2_df$model <- "Douglas fir"
r2_pp <- as.data.frame(r2beta(an_pp))
r2_pp$model <- "Ponderosa pine"
r2_es <- as.data.frame(r2beta(an_es))
r2_es$model <- "Engelmann spruce"
r2_an <- bind_rows(r2_df,r2_pp) %>%
  bind_rows(.,r2_es)
#write.csv(r2_an,file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/r2_an.csv")
#edit effect names and reload
```

```{r }
r2_an <- read_csv("/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/r2_an.csv")
ggplot(data = r2_an,aes(color = model)) + 
  geom_pointrange(data = r2_an,aes(x = Effect, y = Rsq,ymin = lower.CL, ymax = upper.CL))
```


### Tree ring & Climate

```{r}
varmt_df <- varmt_df_z %>%
  dplyr::select(PLT_CN,TRE_CN,Year,dds,z.DIA_C,z.CR,z.ppt_pJunSep,z.tmax_FebJul,
                z.BAL,z.SDI,z.SICOND,z.SLOPE,z.solrad_MayAug, z.n_ppt, z.n_tmp)
clim_df <- lmer(log(dds)~
                  #tree variables
                 z.DIA_C+ I(z.DIA_C^2)+#remove log due to standardization
                 z.CR+
                 #climate
                 z.ppt_pJunSep*z.tmax_FebJul+
                 #competition/density
                 z.SDI+#remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #z.solrad_MayAug+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_df)
varmt_pp <- varmt_pp_z %>%
  dplyr::select(PLT_CN,TRE_CN,Year,dds,z.DIA_C,z.CR,z.ppt_pJunSep,z.tmax_JunAug,
                z.BAL,z.SDI,z.SICOND,z.SLOPE,z.solrad_MayAug,z.n_ppt,z.n_tmp)
clim_pp <- lmer(log(dds)~
                     #tree variables
                     z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                     #climate
                     z.ppt_pJunSep*z.tmax_JunAug+#interaction significant
                     #competition/density
                     z.BAL+ #remove /100 due to standardization
                     #site variables
                     z.SICOND+z.SLOPE+
                     #random effects
                     (1+z.DIA_C|TRE_CN)+(1|Year),
                   control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
                   data = varmt_pp)
varmt_es <- varmt_es_z %>%
  dplyr::select(PLT_CN,TRE_CN,Year,dds,z.DIA_C,z.CR,z.ppt_pJunSep,z.tmax_pAug,
                z.BAL,z.SDI,z.SICOND,z.SLOPE,z.solrad_MayAug,z.n_ppt,z.n_tmp)
clim_es <- lmer(log(dds)~
                 #tree variables
                 z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                 z.CR+
                 #climate
                 z.ppt_pJunSep*z.tmax_pAug+ #significant interaction
                 #competition/density
                 z.BAL+#z.PCCF+z.CCF+ #remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
                data = varmt_es)
```

```{r}
lclim_df <- lmer(log(dds)~
                  #tree variables
                 I(log(DIA_C))+ I(z.DIA_C^2)+#remove log due to standardization
                 z.CR+
                 #climate
                 z.ppt_pJunSep*z.tmax_FebJul+
                 #competition/density
                 z.SDI+#remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #z.solrad_MayAug+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_df_z)
clim_pp <- lmer(log(dds)~
                     #tree variables
                     z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                     #climate
                     z.ppt_pJunSep*z.tmax_JunAug+#interaction significant
                     #competition/density
                     z.BAL+ #remove /100 due to standardization
                     #site variables
                     z.SICOND+#z.SLOPE+
                     #random effects
                     (1+z.DIA_C|TRE_CN)+(1|Year),
                   control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
                   data = varmt_pp_z)
clim_es <- lmer(log(dds)~
                 #tree variables
                 z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                 z.CR+
                 #climate
                 z.ppt_pJunSep*z.tmax_pAug+ #significant interaction
                 #competition/density
                 z.BAL+#z.PCCF+z.CCF+ #remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_es_z)
```

#### random effect climate

```{r}
clim_rs_df <- lmer(log(dds)~
                  #tree variables
                 z.DIA_C+I(z.DIA_C^2)+#remove log due to standardization
                 z.CR+
                 #climate
                 z.ppt_pJunSep*z.tmax_FebJul+
                 #competition/density
                 z.SDI+ 
                 #site variables
                 z.SICOND+z.SLOPE+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+ (1+z.ppt_pJunSep|FVS_LOC_CD)+(1|Year),
                control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_df_z)
clim_rs_pp <- lmer(log(dds)~
                     #tree variables
                     z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                     #z.CR+
                     #climate
                     z.ppt_pJunSep*z.tmax_JunAug+#interaction significant
                     #competition/density
                     z.BAL+ #remove /100 due to standardization
                     #site variables
                     z.SICOND+z.SLOPE+
                     #random effects
                     (1+z.DIA_C|TRE_CN)+(1+z.tmax_JunAug|FVS_LOC_CD)+(1|Year),
                   control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
                   data = varmt_pp_z)
clim_rs_es <- lmer(log(dds)~
                 #tree variables
                 z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                 z.CR+
                 #climate
                 z.ppt_pJunSep*z.tmax_pAug+ #significant interaction
                 #competition/density
                 z.BAL+#z.PCCF+z.CCF+ #remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1+z.ppt_pJunSep|FVS_LOC_CD)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_es_z)
VarCorr(clim_rs_df)
VarCorr(clim_rs_pp)
VarCorr(clim_rs_es)
```

```{r}
#plot r2
r2_df <- as.data.frame(r2beta(clim_rs_df))
r2_df$model <- "Douglas fir"
r2_pp <- as.data.frame(r2beta(clim_rs_pp))
r2_pp$model <- "Ponderosa pine"
r2_es <- as.data.frame(r2beta(clim_rs_es))
r2_es$model <- "Engelmann spruce"
r2_rs <- bind_rows(r2_df,r2_pp) %>%
  bind_rows(.,r2_es)
#write.csv(r2_rs,file = "./data/formatted/r2_rs.csv")
#edit effect names and reload
```
```{r }
r2_rs <- read_csv("/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/r2_rs.csv")
ggplot(data = r2_rs,aes(color = model)) + 
  geom_pointrange(data = r2_rs,aes(x = Effect, y = Rsq,ymin = lower.CL, ymax = upper.CL))
```


```{r }
r2_clim <- read_csv("/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/r2_clim.csv")
ggplot(data = r2_clim,aes(color = model)) + 
  geom_pointrange(data = r2_clim,aes(x = Effect, y = Rsq,ymin = lower.CL, ymax = upper.CL))
```


### Climate Normals

```{r}
n_df <- lmer(log(dds)~
                  #tree variables
                 z.DIA_C+ I(z.DIA_C^2)+#remove log due to standardization
                 z.CR+
                 #climate
                 z.ppt_pJunSep+z.tmax_FebJul+
                 #z.ppt_pJunSep:z.tmax_FebJul+
                 #z.n_ppt+
                 z.n_tmp+
                 z.n_ppt:z.ppt_pJunSep+
                 #z.n_tmp:z.ppt_pJunSep+
                 #z.n_tmp:z.tmax_FebJul+
                 z.n_ppt:z.tmax_FebJul+
                 #competition/density
                 z.SDI+#remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_df)
n_pp <- lmer(log(dds)~
                     #tree variables
                     z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                     #climate
                     z.ppt_pJunSep+z.tmax_JunAug+#interaction significant
                     z.ppt_pJunSep:z.tmax_JunAug+
                     #z.n_ppt+z.n_tmp+
                     z.n_ppt:z.ppt_pJunSep+
                     z.n_tmp:z.ppt_pJunSep+
                     #z.n_ppt:z.tmax_JunAug+
                     #competition/density
                     z.BAL+ #remove /100 due to standardization
                     #site variables
                     z.SICOND+
                     #random effects
                     (1+z.DIA_C|TRE_CN)+(1|Year),
                   control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
                   data = varmt_pp)
n_es <- lmer(log(dds)~
                 #tree variables
                 z.DIA_C+I(z.DIA_C^2)+ #remove log due to standardization
                 z.CR+
                 #climate
                 z.ppt_pJunSep+z.tmax_pAug+ #significant interaction
                 #z.ppt_pJunSep:z.tmax_pAug+
                 z.n_ppt+z.n_tmp+
                 z.n_ppt:z.ppt_pJunSep+
                 z.n_tmp:z.ppt_pJunSep+
                 z.n_tmp:z.tmax_pAug+
                 #competition/density
                 z.BAL+#z.PCCF+z.CCF+ #remove /100 due to standardization
                 #site variables
                 z.SICOND+z.SLOPE+
                 #random effects
                 (1+z.DIA_C|TRE_CN)+(1|Year),
                 control = lmerControl(optimizer = "Nelder_Mead",optCtrl = list(maxfun = 100000)),
               data = varmt_es)
```

```{r}
#plot r2
r2_df <- as.data.frame(r2beta(n_df))
r2_df$model <- "Douglas fir"
r2_pp <- as.data.frame(r2beta(n_pp))
r2_pp$model <- "Ponderosa pine"
r2_es <- as.data.frame(r2beta(n_es))
r2_es$model <- "Engelmann spruce"
r2_n <- bind_rows(r2_df,r2_pp) %>%
  bind_rows(.,r2_es)
#write.csv(r2_n,file = "./data/formatted/r2_n.csv")
#edit effect names and reload
```

```{r }
r2_n <- read_csv("/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/r2_n.csv")
ggplot(data = r2_n,aes(color = model)) + 
  geom_pointrange(data = r2_n,aes(x = Effect, y = Rsq,ymin = lower.CL, ymax = upper.CL))
```

## Summarize output

```{r}
#prep fvs
#load fvs output
load(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/projection/proj_foc.Rdata")
#get observations
#don't want second projection before 2020
load('/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/projection/red clim/red_acc85.Rdata')
obs <-  red_acc85 %>%
  group_by(TRE_CN) %>%
  filter(Year == MEASYEAR) %>%
  dplyr::select(PLT_CN,TRE_CN,SPCD,Year,DIA)
plt_no_fclim <- red_acc85 %>% filter(Year < 2060) %>% filter(is.na(DIA)) #error - some climate data didn't match
plt_no_fclim <- unique(plt_no_fclim$PLT_CN) #remove these plots
rm(red_acc85)

colnames(proj_foc)[colnames(proj_foc)=="DIA"] <- "DIA_0" #more intuitive column names
colnames(proj_foc)[colnames(proj_foc)=="DBH"] <- "DIA"
fvs <- proj_foc %>%
  mutate(PLT_CN = as.numeric(PLT_CN)) %>%
  filter(!(PLT_CN %in% plt_no_fclim)) %>% #remove
  dplyr::select(PLT_CN,TRE_CN,SPCD,Year,DIA_0,DIA) %>%
  filter(Year >= 2020 & Year <= 2060) %>% #remove projection before 2020
  bind_rows(obs) %>% #add back observations
  arrange(Year) %>%
  group_by(TRE_CN) %>%
  mutate(dg_5 = DIA - lag(DIA),
         pct_5 = ((DIA - lag(DIA))/lag(DIA))*100,
         dg_cum = max(DIA) - min(DIA),
         pct_cum = ((max(DIA) - min(DIA))/min(DIA))*100,
         model = as.factor("fvs"))
rm(proj_foc)

#dbh summary output
dia_sum_op <- fvs %>%
    dplyr::select(PLT_CN,TRE_CN,SPCD,model,Year,DIA,dg_5,pct_5) %>%
    filter(Year > 2020) %>%
    mutate(bins = cut(DIA, 
                      breaks=c(3,8,13,18,23,28,33,38), 
                      labels=c("3_8","8_13","13_18","18_23","23_28","28_33","33_38"))) %>%
    group_by(SPCD,model,bins) %>%
    summarise(mn_dg = mean(dg_5),
              mn_pct = mean(pct_5))
saveRDS(dia_sum_op, file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/dia_sum_op.rds")

#mixed model output
mm_op <- data.frame(model = character(), SPCD = double(),
                      dg.diff = double(),
                      dg.se = double(),
                      pct.diff = double(),
                      pct.se = double(),
                      rcp = factor())
saveRDS(mm_op, file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/mm_op.rds")

#t test output
ttest_op <- data.frame(model = character(), SPCD = double(),
                     dg.diff = double(),
                     dg.cilo = double(),
                     dg.cihi = double(),
                     pct.diff = double(),
                     pct.cilo = double(),
                     pct.cihi = double(),
                     rcp = factor())
saveRDS(ttest_op, file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/ttest_op.rds")
```

```{r}
#get file names
full_paths <- paste0('/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/projection/outputs/', 
                     dir('/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/projection/outputs/'))

#run function over each file, or model output
lapply(full_paths, function(x) {
  
  filename <- word(x, -1, sep = '/')
  file_string <- str_remove(filename, '.rds')
  model_name <- word(file_string, 1, sep = "_")
  rcp <- str_sub(file_string, start = -2)
  
  fvs_red <- fvs %>%
    dplyr::select(TRE_CN,SPCD,Year)
  
  new_mod <- readRDS(file = x)
  new_mod <- new_mod %>%
    filter(!(PLT_CN %in% plt_no_fclim)) %>% #remove
    dplyr::select(PLT_CN,TRE_CN,SPCD,Year,DIA) %>%
    inner_join(fvs_red) %>% #should filter for every five years and remove plots where climate didn't match
    arrange(Year) %>%
    group_by(TRE_CN) %>%
    mutate(dg_5 = DIA - lag(DIA),
           pct_5 = ((DIA - lag(DIA))/lag(DIA))*100,
           dg_cum = max(DIA) - min(DIA),
           pct_cum = ((max(DIA) - min(DIA))/min(DIA))*100,
           model = model_name)
  
  #dbh summary script
  dia_sum_df <- new_mod %>%
    dplyr::select(PLT_CN,TRE_CN,SPCD,model,Year,DIA,dg_5,pct_5) %>%
    filter(Year > 2020) %>%
    mutate(bins = cut(DIA, 
                      breaks=c(3,8,13,18,23,28,33,38), 
                      labels=c("3_8","8_13","13_18","18_23","23_28","28_33","33_38"))) %>%
    group_by(SPCD,model,bins) %>%
    summarise(mn_dg = mean(dg_5),
              mn_pct = mean(pct_5)) %>%
    mutate(rcp = rcp)
  #bind to all model summary
  dia_sum_op <- readRDS(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/dia_sum_op.rds")
  dia_sum_op <- bind_rows(dia_sum_op,dia_sum_df)
  saveRDS(dia_sum_op, file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/dia_sum_op.rds")
  rm(dia_sum_op)
  
  #mixed model script
  require(lme4)
  #stacked df
  mm_df <- bind_rows(new_mod,fvs) %>%
    filter(Year == 2060) %>%
    dplyr::select(PLT_CN, TRE_CN, SPCD, model, dg_cum, pct_cum) %>%
    distinct() #just to make sure not getting replicate trees in there
  #make sure fvs is first level in order to get difference in estimate
  mm_df$model <- factor(mm_df$model, levels = c("fvs", model_name))
  mm_df$SPCD <- factor(mm_df$SPCD, levels = c("93", "122", "202"))
  
  mod_comp_dg <- lmer(dg_cum ~ model*SPCD + (1|TRE_CN),
                        data = mm_df)
  mod_comp_pct <- lmer(pct_cum ~ model*SPCD + (1|TRE_CN),
                        data = mm_df)
  mm_comp_df <- data.frame(model = model_name, SPCD = c(93,122,202),
                      dg.diff = summary(mod_comp_dg)$coef[c(2,5,6),1],
                      dg.se = summary(mod_comp_dg)$coef[c(2,5,6),2],
                      pct.diff = summary(mod_comp_pct)$coef[c(2,5,6),1],
                      pct.se = summary(mod_comp_pct)$coef[c(2,5,6),2],
                      rcp = rcp)
  mm_op <- readRDS(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/mm_op.rds")
  mm_op <- bind_rows(mm_op,mm_comp_df)
  saveRDS(mm_op, file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/mm_op.rds")
  rm(mm_op)
  
  #t.test script
  #join
  fvs_t <- fvs %>%
    mutate(fvs_dg = dg_cum,
           fvs_pct = pct_cum) %>%
    dplyr::select(PLT_CN,TRE_CN,SPCD,fvs_dg,fvs_pct) %>%
    distinct()
  t_df <- new_mod %>%
    dplyr::select(PLT_CN,TRE_CN,SPCD,dg_cum,pct_cum) %>%
    distinct() %>%
    inner_join(.,fvs_t)
  #dg
  test_dg_df <- t.test(t_df$dg_cum[t_df$SPCD == 202],t_df$fvs_dg[t_df$SPCD == 202], 
                       paired = TRUE, alternative = "two.sided")
  test_dg_pp <- t.test(t_df$dg_cum[t_df$SPCD == 122],t_df$fvs_dg[t_df$SPCD == 122], 
                       paired = TRUE, alternative = "two.sided")
  test_dg_es <- t.test(t_df$dg_cum[t_df$SPCD == 93],t_df$fvs_dg[t_df$SPCD == 93], 
                       paired = TRUE, alternative = "two.sided")
  #pct
  test_pct_df <- t.test(t_df$pct_cum[t_df$SPCD == 202],t_df$fvs_pct[t_df$SPCD == 202], 
                       paired = TRUE, alternative = "two.sided")
  test_pct_pp <- t.test(t_df$pct_cum[t_df$SPCD == 122],t_df$fvs_pct[t_df$SPCD == 122], 
                       paired = TRUE, alternative = "two.sided")
  test_pct_es <- t.test(t_df$pct_cum[t_df$SPCD == 93],t_df$fvs_pct[t_df$SPCD == 93], 
                       paired = TRUE, alternative = "two.sided")
  
  t_op <- data.frame(model = model_name, SPCD = c(93, 122, 202),
                     dg.diff = c(test_dg_es$estimate,test_dg_pp$estimate,test_dg_df$estimate),
                     dg.cilo = c(test_dg_es$conf.int[1],test_dg_pp$conf.int[1],test_dg_df$conf.int[1]),
                     dg.cihi = c(test_dg_es$conf.int[2],test_dg_pp$conf.int[2],test_dg_df$conf.int[2]),
                     pct.diff = c(test_pct_es$estimate,test_pct_pp$estimate,test_pct_df$estimate),
                     pct.cilo = c(test_pct_es$conf.int[1],test_pct_pp$conf.int[1],test_pct_df$conf.int[1]),
                     pct.cihi = c(test_pct_es$conf.int[2],test_pct_pp$conf.int[2],test_pct_df$conf.int[2]),
                     rcp = rcp)
  ttest_op <- readRDS(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/ttest_op.rds")
  ttest_op <- bind_rows(ttest_op,t_op)
  saveRDS(ttest_op, file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/ttest_op.rds")
  rm(new_mod,ttest_op)
})

```

```{r}
#dbh distribution for each stage - calibration, validation, projection

#calibration
load('/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/varmt_df_z.Rdata')
load('/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/varmt_pp_z.Rdata')
load('/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/varmt_es_z.Rdata')
#filter for DIA in measurement year
cal_dia_df <- varmt_df_z %>%
  ungroup() %>%
  group_by(TRE_CN) %>%
  mutate(DIA = max(DIA_C),
         data = "calibration",
         SPCD = 202) %>%
  dplyr::select(TRE_CN,SPCD,DIA,data) %>%
  distinct()
cal_dia_pp <- varmt_pp_z %>%
  ungroup() %>%
  group_by(TRE_CN) %>%
  mutate(DIA = max(DIA_C),
         data = "calibration",
         SPCD = 122) %>%
  dplyr::select(TRE_CN,SPCD,DIA,data) %>%
  distinct()
cal_dia_es <- varmt_es_z %>%
  ungroup() %>%
  group_by(TRE_CN) %>%
  mutate(DIA = max(DIA_C),
         data = "calibration",
         SPCD = 93) %>%
  dplyr::select(TRE_CN,SPCD,DIA,data) %>%
  distinct()

cal_dia <- bind_rows(cal_dia_df,cal_dia_pp) %>% bind_rows(.,cal_dia_es)

#validation
load('/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/val_dset.Rdata')
ggplot(val_dset, aes(x = DIA, color = as.factor(SPCD))) +
  geom_histogram(fill="white", position="dodge") +
  theme_bw() + labs(main = 'Validation Data Set')
#filter to plot with other data sets
val_dia <- val_dset %>%
  ungroup() %>%
  mutate(TRE_CN = as.numeric(TRE_CN),
         data = "validation") %>%
  dplyr::select(TRE_CN,SPCD,DIA,data)

#projection
load('/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/proj_dset.Rdata')
ggplot(proj_dset, aes(x = DIA, color = as.factor(SPCD))) +
  geom_histogram(fill="white", position="dodge") +
  theme_bw() + labs(main = 'Projection Data Set')

#rug
rug_dg <- ggplot(proj_dset[proj_dset$SPCD == 202,],aes(x = DIA, y = DIA)) +
  geom_rug(alpha = 0.5, sides = "b") +
  theme_bw() + theme(axis.ticks = element_blank()) +
  xlim(0,40)
ggsave(filename = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/images/rug_df.png",
       width = 10, height = 3, units = "in")

ggplot(proj_dset[proj_dset$SPCD == 122,],aes(x = DIA, y = DIA)) +
  geom_rug(alpha = 0.5, sides = "b") +
  theme_bw() + labs(main = 'Projection Data Set') +
  xlim(0,40)

ggplot(proj_dset[proj_dset$SPCD == 93,],aes(x = DIA, y = DIA)) +
  geom_rug(alpha = 0.3, sides = "b") +
  theme_bw() + labs(main = 'Projection Data Set') +
  xlim(0,40)

#filter to plot with others
proj_dia <- proj_dset %>%
  ungroup() %>%
  mutate(TRE_CN = as.numeric(TRE_CN),
         data = "projection") %>%
  dplyr::select(TRE_CN,SPCD,DIA,data)

#together by species
dia_all <- bind_rows(cal_dia,val_dia) %>% bind_rows(.,proj_dia)
dia_all$data <- factor(dia_all$data, levels = c("calibration","validation","projection"))
dia_mu <- dia_all %>%
  group_by(data) %>%
  mutate(mn.dia = mean(DIA))
ggplot(dia_all, aes(x = DIA, color = data)) +
  geom_density() +
  geom_vline(data=dia_mu, aes(xintercept=mn.dia, color=data),
             linetype="dashed")+
  scale_color_brewer(palette="Paired") +
  facet_grid(SPCD~.) +
  theme_bw()

```


```{r}
#function which
proj_mm <- function(fvs,new_mods, rcp, trbl_plt){
  require(tidyverse)
  
  sp_df <- data.frame()
  
  for(i in 1:length(new_mods)){
    mod_name <- names(new_mods)[i]
    mod_new <- new_mods[[i]]
    #get observations
    obs <- mod_new %>%
      group_by(TRE_CN) %>% #for each tree
      filter(Year == MEASYEAR) %>% #select observations
      dplyr::select(PLT_CN,TRE_CN,SPCD,Year,DIA)
    
    #fvs df
    fvs <- fvs %>%
      mutate(PLT_CN = as.numeric(PLT_CN),
             DIA = DBH) %>%
      dplyr::select(PLT_CN,TRE_CN,SPCD,Year,DIA) %>%
      filter(Year >= 2020 & Year <= 2060) %>%
      bind_rows(obs) %>%
      arrange(Year) %>%
      group_by(TRE_CN) %>%
      mutate(dg = DIA - lag(DIA),
             pct = ((DIA - lag(DIA))/lag(DIA))*100,
             model = as.factor("fvs"))
    
    #new model df
    #first new df of fvs to filter every 5 years
    fvs_red <- fvs %>%
      dplyr::select(TRE_CN,SPCD,Year)
    mod_new <- mod_new %>%
      dplyr::select(PLT_CN,TRE_CN,SPCD,Year,DIA) %>%
      inner_join(fvs_red) %>% #should filter for every five years
      arrange(Year) %>%
      group_by(TRE_CN) %>%
      mutate(dg = DIA - lag(DIA),
             pct = ((DIA - lag(DIA))/lag(DIA))*100,
             model = as.factor(mod_name))
    
    #both models df
    new_fvs <- bind_rows(mod_new,fvs) %>%
      mutate(SPCD = as.factor(SPCD)) %>%
      filter(Year > 2020)
    #make sure fvs is first level in order to get difference in estimate
    new_fvs$model <- factor(new_fvs$model, levels = c("fvs", mod_name))
    
    #species-specific mixed model
    require(lme4)
    #df
    new_fvs_df <- 
    mod_comp_df <- lmer(pct ~ model*SPCD*Year + (1|TRE_CN),
                     data = new_fvs)
  }
  
  
}
```



```{r}
#average rcp26
red_26 <- list(bcc = red_bcc26, can = red_can26, ccs = red_ccs26,
               ces = red_ces26, csr = red_csr26, fgl = red_fgl26,
               fio = red_fio26, gfc = red_gfc26, gfg = red_gfg26,
               gfm = red_gfm26, gis = red_gis26, had = red_had26,
               hada = red_hada26, ipm = red_ipm26, mir = red_mir26,
               mpl = red_mpl26, mpm = red_mpm26, mrc = red_mrc26,
               mre = red_mre26, mri = red_mri26, nor = red_nor26)
#average rcp85
red_85 <- list(acc = red_acc85, bcc = red_bcc85, bccm = red_bccm85,
               can = red_can85, ccs = red_ccs85, ces = red_ces85, 
               cmc = red_cmc85, cnm = red_cnm85, csr = red_csr85, 
               fgl = red_fgl85, fio = red_fio85, gfc = red_gfc85, 
               gfg = red_gfg85, gfm = red_gfm85, gis = red_gis85, 
               had = red_had85, hada = red_hada85, hadc = red_hadc85,
               inm = red_inm85, ipl = red_ipl85,  ipm = red_ipm85, 
               mir = red_mir85, mpl = red_mpl85, mpm = red_mpm85, 
               mrc = red_mrc85, mre = red_mre85, mri = red_mri85, nor = red_nor85)

```


```{r}
#visualize dg by diameter
dia_sum_op <- readRDS(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/dia_sum_op.rds")
#summarize by model and rcp
dia_sum_all <- dia_sum_op %>%
  group_by(SPCD,model,rcp,bins) %>%
    summarise(mn_dg_all = mean(mn_dg),
              mn_pct_all = mean(mn_pct)) %>%
  unite("scenario", model:rcp, na.rm = TRUE, remove = FALSE) %>%
  separate(bins, c("start", "end"), "_")

#allows for lines
dia_sum_all$start <- as.numeric(dia_sum_all$start)
#dia_sum_all$bins <- factor(dia_sum_all$bins,levels = c("3_8","8_13","13_18","18_23","23_28","28_33","33_38"))

#relative growth
ggplot(data = dia_sum_all, aes(x = start, y = mn_pct_all, color = scenario)) +
  geom_line() + xlab("Diameter") +
  facet_grid(.~SPCD)

#absolute growth
ggplot(data = dia_sum_all, aes(x = start, y = mn_dg_all, color = scenario)) +
  geom_line() + xlab("Diameter") +
  facet_grid(.~SPCD)
```

```{r}
#get difference with fvs
dia_fvs <- dia_sum_op %>%
  ungroup() %>%
  filter(model == "fvs") %>%
  mutate(fvs_pct = mn_pct) %>%
  dplyr::select(SPCD,bins,fvs_pct)
dia_diff_all <- dia_sum_op %>%
  filter(model != "fvs") %>%
  left_join(.,dia_fvs) %>%
  mutate(pct_diff = mn_pct - fvs_pct,
         DIA_class = ifelse(bins == "3_8", 5,
                        ifelse(bins == "8_13", 10,
                           ifelse(bins == "13_18", 15,
                              ifelse(bins == "18_23", 20,
                                 ifelse(bins == "23_28", 25,
                                    ifelse(bins == "28_33", 30, 35))))))) %>%
  dplyr::select(SPCD,model,rcp,bins,pct_diff,DIA_class) %>%
  unite("scenario", model:rcp, na.rm = TRUE, remove = FALSE)
dia_diff_all$bins <- factor(dia_diff_all$bins,levels = c("3_8","8_13","13_18","18_23","23_28","28_33","33_38"))
#relevel scenario so reduced annual is in the middle
dia_diff_all$scenario <- factor(dia_diff_all$scenario, levels = c("red_26","red_85","tr_an", "n_26", "n_85","nint_26","nint_85"))

#too much information, get rid of normals + interactions
dia_diff_df <- dia_diff_all %>% filter(SPCD == 202) %>% filter(model != "nint") 
dia_diff_pp <- dia_diff_all %>% filter(SPCD == 122) %>% filter(model != "nint")
dia_diff_es <- dia_diff_all %>% filter(SPCD == 93) %>% filter(model != "nint")


#plot
proj_dia_df <- ggplot(data = dia_diff_df, aes(x = bins, y = pct_diff)) +
  geom_violin(aes(fill = scenario), width=6, position=position_dodge(width=0.6)) + 
  scale_fill_manual(values=c("grey81","gray44","grey81","gray44")) +
  stat_summary(fun="mean",color="dodgerblue3", geom="point", aes(shape = scenario), size=2,
               position=position_dodge(width=.55)) +
  scale_shape_manual(values=c(2,2,1,3,3)) +
  geom_hline(yintercept = 0, colour = "grey60", linetype = 2) +
  theme_bw() + labs(x = "Diameter Class", y = "Difference in relative growth", shape = "Model", fill = "Climate Scenario" )
ggsave(filename = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/images/proj_dia_df.png",
       width = 10, height = 3, units = "in")

proj_dia_pp <- ggplot(data = dia_diff_pp, aes(x = bins, y = pct_diff)) +
  geom_violin(aes(fill = scenario), width=6, position=position_dodge(width=0.6)) + 
  scale_fill_manual(values=c("grey81","gray44","grey81","gray44")) +
  stat_summary(fun="mean",color="dodgerblue3", geom="point", aes(shape = scenario), size=2,
               position=position_dodge(width=.55)) +
  scale_shape_manual(values=c(2,2,1,3,3))  +
  geom_hline(yintercept = 0, colour = "grey60", linetype = 2) +
  theme_bw() + labs(x = "Diameter Class", y = "Difference in relative growth", shape = "Model", fill = "Climate Scenario" )
ggsave(filename = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/images/proj_dia_pp.png",
       width = 10, height = 3, units = "in")

proj_dia_es <- ggplot(data = dia_diff_es, aes(x = bins, y = pct_diff)) +
  geom_violin(aes(fill = scenario), width=6, position=position_dodge(width=0.6)) + 
  scale_fill_manual(values=c("grey81","gray44","grey81","gray44")) +
  stat_summary(fun="mean",color="dodgerblue3", geom="point", aes(shape = scenario), size=2,
               position=position_dodge(width=.55)) +
  scale_shape_manual(values=c(2,2,1,3,3))  +
  geom_hline(yintercept = 0, colour = "grey60", linetype = 2) +
  theme_bw() + labs(x = "Diameter Class", y = "Difference in relative growth", shape = "Model", fill = "Climate Scenario" )
ggsave(filename = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/images/proj_dia_es.png",
       width = 10, height = 3, units = "in")


```

```{r}
#visualize ttest
ttest_op <- readRDS(file = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/data/formatted/ttest_op.rds")
ttest_op$model <- factor(ttest_op$model, levels = c("tr","red", "n","nint"), 
                          labels = c("Reduced Annual","Reduced Climate", "Climate Normals", "Normals + Interactions"))
ttest_op$rcp <- factor(ttest_op$rcp, levels = c("an","26", "85"), 
                          labels = c("No Climate","RCP2.6", "RCP8.5")) 
ttest_op$rcp <- factor(ttest_op$rcp, levels = c("No Climate","RCP2.6", "RCP8.5")) 

#get average
ttest_all <- ttest_op %>%
  group_by(model,rcp,SPCD) %>%
  summarise(mn.dg.dif = mean(dg.diff),
            mn.pct.dif = mean(pct.diff)) #%>%
  #unite("scenario", model:rcp, na.rm = TRUE, remove = FALSE)

#plot
proj_cum_df <- ggplot(ttest_op[ttest_op$SPCD == 202,], aes(x = rcp, y = pct.diff, color = model)) +
  #add rcp26 rect
  geom_rect(xmin = as.numeric(ttest_op$rcp[[3]]) - 1.5,
            xmax = as.numeric(ttest_op$rcp[[3]]) - 0.5, 
            ymin = -Inf, ymax = Inf,
            fill = "grey81", alpha =.2) +
  #add rcp285 rect
  geom_rect(xmin = as.numeric(ttest_op$rcp[[3]]) - 0.5,
            xmax = as.numeric(ttest_op$rcp[[3]]) + Inf, 
            ymin = -Inf, ymax = Inf,
            fill = "gray44", alpha =.2) +
  geom_violin(show.legend = F) +
  scale_color_manual(values = c("black","black","black","black")) +
  #facet_grid(.~as.factor(SPCD)) +
  geom_point(data = ttest_all[ttest_all$SPCD == 202,], 
             aes(x = as.factor(rcp), y = mn.pct.dif, shape = model), 
             size = 2, color = "dodgerblue3",
             position=position_dodge(width = 0.9)) +
  scale_shape_manual(values=c(1,2,3,8)) +# change shape 
  theme_bw() + labs(x = "Climate Scenario", y = "Difference in cumulative relative growth")
ggsave(filename = "/home/courtney/Documents/Masters/Research/Utah/UT_FVS/images/proj_cum_df.png",
       width = 5, height = 3, units = "in")
```

